### ISSUE TITLE
Invalid plugin.yml - plugin will not start

### ISSUE THREAD

**Issue by tmad40blue** [RobiRami/LeaderHeads#1]
Hi, the latest build of LeaderHeads (10.2.4) won't start, it complains about an invalid plugin.yml -

```
[10:25:44] [Server thread/ERROR]: Could not load 'plugins/LeaderHeads.jar' in folder 'plugins'                                                                
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml                                                                                             
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot.jar:git-Spigot-1a196e1-09b4549]                   
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-1a196e1-09b4549]                            
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-1a196e1-09b4549]                               
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot.jar:git-Spigot-1a196e1-09b4549]                                
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot.jar:git-Spigot-1a196e1-09b4549]                                 
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]                                                                                                 
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)                                                                                     
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_66]                                                                                            
        at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_66]                                                                                       
        at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_66]                                                                                       
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_66]                                                                                       
        at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_66]                                                                                       
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot.jar:git-Spigot-1a196e1-09b4549]                   
        ... 5 more
```

**Comment by RobiRami** [comment]
Open the file with Winrar and then press Control+C

**Comment by RobiRami** [comment]
I mean Control+S.
Try redownloading the plugin as well.

**Comment by tmad40blue** [comment]
Redownloading did the trick, thanks.

P.S.: Not everyone uses Windows - I'm a full-time Linux user - so it might be good to offer some platform-independent advice were someone to come along the same issue.

**Comment by RobiRami** [comment]
Thanks for the information.
I will add this issue to the FAQ.
