### ISSUE TITLE
IllegalArgumentException for "drop" board type

### ISSUE THREAD

**Issue by tmad40blue** [RobiRami/LeaderHeads#2]
Hi, I've got some boards that are tracking item drops, and they're not properly accepting the placeholders, and also printing this error in my server console:

```
[14:34:13 WARN]: java.lang.IllegalArgumentException: Must supply additional paramater for this statistic
[14:34:13 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[14:34:13 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftPlayer.getStatistic(CraftPlayer.java:560)
[14:34:13 WARN]:        at me.robin.leaderheads.Y.x$1.getData(VanillaBoard.java:113)
[14:34:13 WARN]:        at me.robin.leaderheads.objects.LeaderBoard$3.run(LeaderBoard.java:234)
[14:34:13 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[14:34:13 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:34:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:34:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:34:13 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by RobiRami** [comment]
I'm not sure if the 'drop' statistic changed in 1.9, so I think it is a bug in Spigot itself. I will report it soon.

**Comment by RobiRami** [comment]
This should be fixed: https://hub.spigotmc.org/jira/browse/SPIGOT-1920
